### ISSUE TITLE
Improve loading rules

### ISSUE THREAD

**Issue by asdofindia** [libindic/normalizer#6]
- [ ] Use `with` style opening for automatically closing the file after reading
- [ ] python3 compatibiity
- [ ] Use `for` to loop through all lines
- [ ] Simplify ignoring comments
- [ ] Simplify rule syntax (is "" necessary?)

**Comment by balasankarc** [comment]
@santhoshtr @copyninja I second these suggestions. We can fix on rule styles (like, don't use quotes) and it will help much in reducing complexity of the LoadRules method. Flake8 is complaining that it is too complex.

**Comment by copyninja** [comment]
Go ahead.  You don't need our permission to fix things or improvement
